name: cotlear_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_map: ^7.0.2
  flutter_riverpod: ^2.5.1
  geolocator: ^12.0.0
  go_router: ^14.2.0
  google_sign_in: ^6.2.1
  latlong2: ^0.9.1
  supabase_flutter: ^2.5.7

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
