name: cotlear_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  card_swiper: ^3.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_map: ^7.0.2
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  formz: ^0.7.0
  geolocator: ^12.0.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  latlong2: ^0.9.1
  supabase_flutter: ^2.5.7

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app-icon-1.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - .env.development
    - .env.production
    - assets/icon/
